upstream: "http://localhost"
debug: false

metrics:
  enabled: false
  listenAddr: 0.0.0.0:9090
  endpoint: /metrics

server:
  requireTls: false
  listenHttp: 0.0.0.0:8081
  listenHttps: ""

teleport:
  proxyAddr: teleport.lukeelten.de:8443