upstream: "http://localhost:8080"
debug: true
metrics:
  enabled: false
  listenAddr: 0.0.0.0:9090
  endpoint: /metrics

server:
  requireTls: false
  keyFile: "/cert/tls.key"
  certFile: "/cert/tls.crt"
  listenHttp: 0.0.0.0:8081
  listenHttps: 0.0.0.0:8444
  tlsProfile: modern
  appendProxyHeaders: true

teleport:
  proxyAddr: teleport.lukeelten.de:8443